[ALPS08631203] fix build error about include file changed
[Description]
Fix build error according to Commit "6fe236d7" (Merge 3cb9871f8160 ("Merge tag urgent-rcu.2024.01.24a of https://github.com/neeraju/linux") into android-mainline)

../vendor/mediatek/kernel_modules/connectivity/conninfra/conn_drv/connv3/platform/connv3_hw_plat_data.c:26:40: error: array has incomplete element type const struct of_device_id
   26 | const struct of_device_id connv3_of_ids[] = {
      |                                        ^
/kernel-mainline/include/linux/device/driver.h:106:15: note: forward declaration of struct of_device_id
  106 |         const struct of_device_id       *of_match_table;
      |                      ^
1 error generated.

../vendor/mediatek/kernel_modules/connectivity/conninfra/conn_drv/connv3/platform/connv3_pmic_mng.c:67:52: error: array has incomplete element type const struct of_device_id
   67 | const struct of_device_id connv3_pmic_mt6373_of_ids[] = {
      |                                                    ^
/kernel-mainline/include/linux/device/driver.h:106:15: note: forward declaration of struct of_device_id
  106 |         const struct of_device_id       *of_match_table;
      |                      ^
1 error generated.

[Test]
Build and Boot up

MTK-Commit-Id: f656ec935ed4962cf417b4b08fbaebe484ceb26d

Change-Id: Ib5c97f46ed5f13e3f98c1e00f9fd0dde9b604dfa
Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation